# Site settings
title: Yuri Kasperovich's Work Blog
email: ykas.gg@gmail.com
description: "Hello, my name is Yuri Kasperovich, welcome to my work blog"
baseurl: ""
url: "http://yukas.by"
twitter_username: yukas
github_username:  yukas

# Build settings
markdown: kramdown
permalink: pretty

me: Yuri Kasperovich